[project]
name = "otus-mladv-dvc-practice"
version = "0.1.0"
description = "DVC practice for ML Advanced course"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc[s3]==3.61.0",
    "loguru==0.7.3",
    "pandas==2.3.1",
    "scikit-learn==1.7.1",
]
